stages:
  - containerize-dev
  - deploy-dev

containerize-api-dev:
  stage: containerize-dev
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/api/Dockerfile.dev --destination "$CI_REGISTRY_IMAGE"/api:$CI_COMMIT_TAG
  #rules:
  #  - if: $CI_COMMIT_TAG

containerize-client-dev:
  stage: containerize-dev
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/client/Dockerfile.dev --destination "$CI_REGISTRY_IMAGE"/client:$CI_COMMIT_TAG
  #rules:
  #  - if: $CI_COMMIT_TAG