version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
      image: mongo-express
      container_name: mongo-express
      ports:
          - 8081:8081
      environment:
          ME_CONFIG_MONGODB_SERVER: mongodb
          ME_CONFIG_BASICAUTH_USERNAME: root
          ME_CONFIG_BASICAUTH_PASSWORD: password
      depends_on:
          - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
      # Anonymous volume to prevent overwrite
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      REACT_APP_API_URL: http://localhost:4000 # The requests are sent from the local browser (outside Docker network)

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - mongodb
    ports:
      - 4000:4000
    volumes:
      - ./api:/usr/src
      # Anonymous volume to prevent overwrite
      - /usr/src/node_modules
    environment:
      # https://github.com/ufoscout/docker-compose-wait/
      WAIT_HOSTS: mongodb:3306
